taco:
  orders:
    pageSize: 20
spring:
  application:
    name: taco-cloud
  profiles:
    default: prod
---
spring:
  config:
    activate:
      on-profile: prod
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
logging:
  level:
    tacos: WARN
