spring:
  config:
    import: classpath:secrets.yml
  application:
    name: main
  profiles:
    default: test
  data:
    rest:
      base-path: /rest-api
security:
  jwt:
    token-expire-in-minutes: 30
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
